import Head from "next/head";
import styles from "@/styles/Home.module.css";

import MainNav from "@/components/MainNav";
import { Titillium_Web } from 'next/font/google';

const titillium = Titillium_Web({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Dont Blow Yourself Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${titillium.className}`}
      >
        <main className={styles.main}>
         <MainNav/>
        </main>

      </div>
    </>
  );
}
